### PR TITLE
Enhancements/fixes related to coordinate epochs

### LINKED ISSUE #3995: Proposal: add in_coord_epoch and out_coord_epoch optional argments in filters.reprojection for time-based coordinate transformations
There's currently no easy way to do coordinate transformations with PDAL's filters.reprojection.

For example in https://github.com/PDAL/PDAL/issues/3975, for static CRS -> dynamic CRS or dynamic CRS -> static CRS, the workaround is to write a PROJ pipeline using +set v_4= to set the source or target coordinate epoch.
In the future PROJ may also support dynamic CRS at epoch A -> dynamic CRS at epoch B transformations, that would make writing such pipelines even more complicated.

One possibility currenly would be to use the WKT2:2019 [COORDINATEMETADATA](https://docs.ogc.org/is/18-010r7/18-010r7.html#130) construct that is supported since PROJ 9.2 to fill the in_srs and out_srs arguments of filters.reprojection. But this is quite verbose. I would propose to add ``in_coord_epoch`` and ``out_coord_epoch`` optional arguments, pass them to PDAL's  SrsTransform, which will forward them to GDAL's OGRSpatialReference::SetCoordinateEpoch().

This will allow users to use EPSG codes in ``in_srs`` and ``out_srs`` for compactness , like ``in_srs="EPSG:8255"``, ``out_srs="EPSG:8255"``, ``in_coord_epoch=2023.1``, ``out_coord_epoch=2002``, instead of ``in_srs=COORDINATEMETADATA[GEOGCRS[\"NAD83(CSRS)v7\",DATUM[\"North American Datum of 1983 (CSRS) version 7\",ELLIPSOID[\"GRS 1980\",6378137,298.257222101,LENGTHUNIT[\"metre\",1]]],PRIMEM[\"Greenwich\",0,ANGLEUNIT[\"degree\",0.0174532925199433]],CS[ellipsoidal,2],AXIS[\"geodetic latitude (Lat)\",north,ORDER[1],ANGLEUNIT[\"degree\",0.0174532925199433]],AXIS[\"geodetic longitude (Lon)\",east,ORDER[2],ANGLEUNIT[\"degree\",0.0174532925199433]],USAGE[SCOPE[\"Horizontal component of 3D system.\"],AREA[\"Canada - onshore and offshore - Alberta; British Columbia; Manitoba; New Brunswick; Newfoundland and Labrador; Northwest Territories; Nova Scotia; Nunavut; Ontario; Prince Edward Island; Quebec; Saskatchewan; Yukon.\"],BBOX[38.21,-141.01,86.46,-40.73]],ID[\"EPSG\",8255]],EPOCH[2023.1])`` and ``out_srs=COORDINATEMETADATA[GEOGCRS[\"NAD83(CSRS)v7\",DATUM[\"North American Datum of 1983 (CSRS) version 7\",ELLIPSOID[\"GRS 1980\",6378137,298.257222101,LENGTHUNIT[\"metre\",1]]],PRIMEM[\"Greenwich\",0,ANGLEUNIT[\"degree\",0.0174532925199433]],CS[ellipsoidal,2],AXIS[\"geodetic latitude (Lat)\",north,ORDER[1],ANGLEUNIT[\"degree\",0.0174532925199433]],AXIS[\"geodetic longitude (Lon)\",east,ORDER[2],ANGLEUNIT[\"degree\",0.0174532925199433]],USAGE[SCOPE[\"Horizontal component of 3D system.\"],AREA[\"Canada - onshore and offshore - Alberta; British Columbia; Manitoba; New Brunswick; Newfoundland and Labrador; Northwest Territories; Nova Scotia; Nunavut; Ontario; Prince Edward Island; Quebec; Saskatchewan; Yukon.\"],BBOX[38.21,-141.01,86.46,-40.73]],ID[\"EPSG\",8255]],EPOCH[2002])``

### PR DESCRIPTION
**Pull request by rouault**
Complements PR #4049, closes #3995 . To be fully effective, it requires https://github.com/OSGeo/PROJ/pull/3884 and https://github.com/OSGeo/gdal/pull/8340, but it can be applied independently as it doesn't use new API

-   SpatialReference::set(): store coordinate epoch from OGRSpatialReference built from SetFromUserInput()
    
    This is useful to get the epoch for a SpatialReference built from a
    string like 'urn:ogc:def:coordinateMetadata:AUTHORTIY::CODE code' (since
    https://github.com/OSGeo/gdal/pull/8340 and https://github.com/OSGeo/PROJ/pull/3884), which
    resolves to a CoordinateMetadata object with a CRS and potentially a
    coordinate epoch

-  SrsTransform: make sure to propagate coordinate epoch when rebuilding OGRSpatialReference objects

-  SpatialReference::set(): when building from SetFromUserInput(), get the WKT2 version
    
    This limits the loss of information, particularly for CRS like
    'urn:ogc:def:coordinateMetadata:NRCAN::NAD83_CSRS_1997_MTM7_HT2_1997'
    which include a GEOIDMODEL[] node, that would be lost otherwise

With that PR and above mentionned GDAL and PROJ PRs,
```
$ cat in.csv
X,Y,Z
268955,5540412,0

$ cat pipeline.json
[
    {
        "type":"readers.text",
        "filename":"in.csv"
    },
    {
        "type":"filters.reprojection",
        "in_srs":"urn:ogc:def:coordinateMetadata:NRCAN::NAD83_CSRS_1997_MTM7_HT2_1997",
        "out_srs":"urn:ogc:def:coordinateMetadata:NRCAN::NAD83_CSRS_2010_UTM19_CGVD2013_2010"
    },
    {
        "type":"writers.text",
        "filename":"outputfile.txt"
    }
]

$ PROJ_NETWORK=ON bin/pdal pipeline pipeline.json

$ cat outputfile.txt 
"X","Y","Z"
356670.104,5540546.584,-0.306
```

hence we get the same results as with gdaltransform and cs2cs with similar invokations

### CODE REVIEW

File: pdal/SpatialReference.cpp [hunk 1]
```diff
@@ -237,7 +237,9 @@ void SpatialReference::set(std::string v)
         throw pdal_error(oss.str());
     }
 
-    m_wkt = exportToWkt(&srs);
+    m_epoch = srs.GetCoordinateEpoch();
+
+    m_wkt = exportToWkt(&srs, {"FORMAT=WKT2_2018"});
```
Comment (hobu) [inline pdal/SpatialReference.cpp:242]: Is `WKT2_2018` the default format for WKT export from GDAL right now already? What flavor would you get if you didn't request this?

**Review by hobu — APPROVED** [review]

**Comment by hobu** [comment]
The one linux failure is something I'm working on fixing...

File: pdal/SpatialReference.cpp (hunk 1 above)
Comment (rouault) [reply pdal/SpatialReference.cpp:242]: > Is `WKT2_2018` the default format for WKT export from GDAL right now already?

no, it is still WKT1_GDAL

Comment (hobu) [reply pdal/SpatialReference.cpp:242]: Hmm, that might break some stuff that expects WKT1.

Comment (rouault) [reply pdal/SpatialReference.cpp:242]: > Hmm, that might break some stuff that expects WKT1.

shouldn't they use the getWKT1() method then ?

I could potentially limit the scope of that change to situations where I detect a GEOID_MODEL in the WKT, but that would be a bit ugly

Comment (hobu) [reply pdal/SpatialReference.cpp:242]: I think I like this better. That way WKT2+ is opt-in and we don't disrupt anyone who might have been assuming WKT1

Comment (rouault) [reply pdal/SpatialReference.cpp]: > I think I like this better. That way WKT2+ is opt-in and we don't disrupt anyone who might have been assuming WKT1

done in the last 3 commits

File: pdal/SpatialReference.hpp [hunk 2]
```diff
@@ -182,12 +182,15 @@ class PDAL_DLL SpatialReference
 
 private:
     std::string m_wkt;
+    mutable std::string m_wkt2;
```
Comment (hobu) [inline pdal/SpatialReference.hpp:185]: I don't understand why this is `mutable` and *m_wkt* isn't.

**Review by hobu — APPROVED** [review]

File: pdal/SpatialReference.hpp (hunk 2 above)
Comment (rouault) [reply pdal/SpatialReference.hpp:185]: > I don't understand why this is `mutable` and _m_wkt_ isn't.

m_wkt is always set in the set() method, whereas m_wkt2 is only set in set() if the WKT is WKT2. Otherwise it is computed on demand in getWKT2() which is const, hence the mutable.
The alternative would be that I always compute m_wkt2, and thus getWKT2() would just return it

Comment (hobu) [reply pdal/SpatialReference.hpp:185]: I think I would rather always compute it in set() so it is clear what's happening, instead of having the scary `mutable` without the comment to tell us why it is mutable.

Comment (rouault) [reply pdal/SpatialReference.hpp]: > I think I would rather always compute it in set() so it is clear what's happening, instead of having the scary `mutable` without the comment to tell us why it is mutable.

done
