### PR TITLE
Fix S3 HEAD requests

### LINKED ISSUE #3955: Reading EPT from S3 broken in 2.5.0 ?
**Description**

Trying to read an ept point cloud from an S3 bucket using PDAL doesn't seem to be working anymore.

I've used the smallest [publicly available](https://usgs.entwine.io/#) EPT to reproduce the problem

```
$ AWS_REGION=us-west-2 pdal info s3://usgs-lidar-public/IL_BooneCo_2007/ept.json
Curl details: Could not resolve host: usgs-lidar-public
Curl details: Could not resolve host: usgs-lidar-public
Curl details: Could not resolve host: usgs-lidar-public
Curl failure: Couldn't resolve host name
Curl details: Could not resolve host: usgs-lidar-public
Curl failure: Couldn't resolve host name
Curl failure: Couldn't resolve host name
...
```

<details>

Failure output keeps being printed periodically, every time at a longer period. Possibly due to the exponential backoff introduced in retries?

Initially I thought the process was stuck in a loop but then realized that actually it returns the result after a very long time (**~8 minutes**). 

See below full execution logs:

* Working on previous PDAL version (2.4.3)
[pdal2.4.3_eptok_run.log](https://github.com/PDAL/PDAL/files/10480648/pdal2.4.3_eptok_run.log)

* Hanging in latest PDAL version (2.5.0) for quite some time (**~8 minutes**) eventually returning
[pdal2.5.0_eptfail_run.log](https://github.com/PDAL/PDAL/files/10480622/pdal2.5.0_eptfail_run.log)

</details>

**Expected behavior**
EPT point cloud should have been read in a matter of seconds and output contain computed statistics for each dimension.

**System/installation information:**

```
$ uname -a
Linux joaori-pc 5.10.161-1-MANJARO #1 SMP PREEMPT Wed Dec 21 21:15:06 UTC 2022 x86_64 GNU/Linux
```

```
$ pdal --version
-------------------------------------------------------------------------------------------------------------------------------------------------------------------
pdal 2.5.0 (git-version: 4f46bc)
-------------------------------------------------------------------------------------------------------------------------------------------------------------------
```

Installed via Conda (micromambda) see details below.

<details>
  
```
$ micromamba list
List of packages in environment: "/home/joaori/var/git/entwine/_dev/dev/micromamba/envs/pdal-test"

  Name                       Version       Build               Channel    
────────────────────────────────────────────────────────────────────────────
  _libgcc_mutex              0.1           conda_forge         conda-forge
  _openmp_mutex              4.5           2_gnu               conda-forge
  blosc                      1.21.3        hafa529b_0          conda-forge
  boost-cpp                  1.78.0        h75c5d50_1          conda-forge
  bzip2                      1.0.8         h7f98852_4          conda-forge
  c-ares                     1.18.1        h7f98852_0          conda-forge
  ca-certificates            2022.12.7     ha878542_0          conda-forge
  cairo                      1.16.0        ha61ee94_1014       conda-forge
  cfitsio                    4.2.0         hd9d235c_0          conda-forge
  curl                       7.87.0        hdc1c0ab_0          conda-forge
  draco                      1.5.5         h924138e_0          conda-forge
  eigen                      3.4.0         h4bd325d_0          conda-forge
  expat                      2.5.0         h27087fc_0          conda-forge
  font-ttf-dejavu-sans-mono  2.37          hab24e00_0          conda-forge
  font-ttf-inconsolata       3.000         h77eed37_0          conda-forge
  font-ttf-source-code-pro   2.038         h77eed37_0          conda-forge
  font-ttf-ubuntu            0.83          hab24e00_0          conda-forge
  fontconfig                 2.14.1        hc2a2eb6_0          conda-forge
  fonts-conda-ecosystem      1             0                   conda-forge
  fonts-conda-forge          1             0                   conda-forge
  freetype                   2.12.1        hca18f0e_1          conda-forge
  freexl                     1.0.6         h166bdaf_1          conda-forge
  geos                       3.11.1        h27087fc_0          conda-forge
  geotiff                    1.7.1         h7a142b4_6          conda-forge
  gettext                    0.21.1        h27087fc_0          conda-forge
  giflib                     5.2.1         h36c2ea0_2          conda-forge
  hdf4                       4.2.15        h9772cbc_5          conda-forge
  hdf5                       1.12.2        nompi_h4df4325_101  conda-forge
  icu                        70.1          h27087fc_0          conda-forge
  jpeg                       9e            h166bdaf_2          conda-forge
  json-c                     0.16          hc379101_0          conda-forge
  kealib                     1.5.0         ha7026e8_0          conda-forge
  keyutils                   1.6.1         h166bdaf_0          conda-forge
  krb5                       1.20.1        h81ceb04_0          conda-forge
  lcms2                      2.14          hfd0df8a_1          conda-forge
  lerc                       4.0.0         h27087fc_0          conda-forge
  libaec                     1.0.6         hcb278e6_1          conda-forge
  libcurl                    7.87.0        hdc1c0ab_0          conda-forge
  libdeflate                 1.17          h0b41bf4_0          conda-forge
  libedit                    3.1.20191231  he28a2e2_2          conda-forge
  libev                      4.33          h516909a_1          conda-forge
  libffi                     3.4.2         h7f98852_5          conda-forge
  libgcc-ng                  12.2.0        h65d4601_19         conda-forge
  libgdal                    3.6.2         h8c90c07_5          conda-forge
  libgfortran-ng             12.2.0        h69a702a_19         conda-forge
  libgfortran5               12.2.0        h337968e_19         conda-forge
  libglib                    2.74.1        h606061b_1          conda-forge
  libgomp                    12.2.0        h65d4601_19         conda-forge
  libiconv                   1.17          h166bdaf_0          conda-forge
  libkml                     1.3.0         h37653c0_1015       conda-forge
  libnetcdf                  4.8.1         nompi_h261ec11_106  conda-forge
  libnghttp2                 1.51.0        hff17c54_0          conda-forge
  libnsl                     2.0.0         h7f98852_0          conda-forge
  libpng                     1.6.39        h753d276_0          conda-forge
  libpq                      15.1          hb675445_3          conda-forge
  librttopo                  1.1.0         ha49c73b_12         conda-forge
  libspatialite              5.0.1         h221c8f1_23         conda-forge
  libsqlite                  3.40.0        h753d276_0          conda-forge
  libssh2                    1.10.0        hf14f497_3          conda-forge
  libstdcxx-ng               12.2.0        h46fd767_19         conda-forge
  libtiff                    4.5.0         h6adf6a1_2          conda-forge
  libuuid                    2.32.1        h7f98852_1000       conda-forge
  libwebp-base               1.2.4         h166bdaf_0          conda-forge
  libxcb                     1.13          h7f98852_1004       conda-forge
  libxml2                    2.10.3        h7463322_0          conda-forge
  libzip                     1.9.2         hc929e4a_1          conda-forge
  libzlib                    1.2.13        h166bdaf_4          conda-forge
  lz4-c                      1.9.3         h9c3ff4c_1          conda-forge
  ncurses                    6.3           h27087fc_1          conda-forge
  nitro                      2.7.dev6      h27087fc_5          conda-forge
  nspr                       4.35          h27087fc_0          conda-forge
  nss                        3.82          he02c5a1_0          conda-forge
  openjpeg                   2.5.0         hfec8fc6_2          conda-forge
  openssl                    3.0.7         h0b41bf4_1          conda-forge
  pcre2                      10.40         hc3806b6_0          conda-forge
  pdal                       2.5.0         h0ea1e05_0          conda-forge
  pixman                     0.40.0        h36c2ea0_0          conda-forge
  poppler                    23.01.0       h091648b_0          conda-forge
  poppler-data               0.4.11        hd8ed1ab_0          conda-forge
  postgresql                 15.1          h3248436_3          conda-forge
  proj                       9.1.1         h8ffa02c_2          conda-forge
  pthread-stubs              0.4           h36c2ea0_1001       conda-forge
  readline                   8.1.2         h0f457ee_0          conda-forge
  snappy                     1.1.9         hbd366e4_2          conda-forge
  sqlite                     3.40.0        h4ff8645_0          conda-forge
  tiledb                     2.13.2        hd532e3d_0          conda-forge
  tzcode                     2022g         h166bdaf_0          conda-forge
  tzdata                     2022g         h191b570_0          conda-forge
  xerces-c                   3.2.4         h55805fa_1          conda-forge
  xorg-kbproto               1.0.7         h7f98852_1002       conda-forge
  xorg-libice                1.0.10        h7f98852_0          conda-forge
  xorg-libsm                 1.2.3         hd9c2040_1000       conda-forge
  xorg-libx11                1.7.2         h7f98852_0          conda-forge
  xorg-libxau                1.0.9         h7f98852_0          conda-forge
  xorg-libxdmcp              1.1.3         h7f98852_0          conda-forge
  xorg-libxext               1.3.4         h7f98852_1          conda-forge
  xorg-libxrender            0.9.10        h7f98852_1003       conda-forge
  xorg-renderproto           0.11.1        h7f98852_1002       conda-forge
  xorg-xextproto             7.3.0         h7f98852_1002       conda-forge
  xorg-xproto                7.0.31        h7f98852_1007       conda-forge
  xz                         5.2.6         h166bdaf_0          conda-forge
  zlib                       1.2.13        h166bdaf_4          conda-forge
  zstd                       1.5.2         h3eb15da_6          conda-forge
```

</details>

<details>
  
```
$ micromamba info

                                           __
          __  ______ ___  ____ _____ ___  / /_  ____ _
         / / / / __ `__ \/ __ `/ __ `__ \/ __ \/ __ `/
        / /_/ / / / / / / /_/ / / / / / / /_/ / /_/ /
       / .___/_/ /_/ /_/\__,_/_/ /_/ /_/_.___/\__,_/
      /_/


            environment : pdal-test (active)
           env location : /home/joaori/var/git/entwine/_dev/dev/micromamba/envs/pdal-test
      user config files : /home/joaori/.mambarc
 populated config files : 
       libmamba version : 1.2.0
     micromamba version : 1.2.0
           curl version : libcurl/7.87.0 OpenSSL/1.1.1s zlib/1.2.13 libssh2/1.10.0 nghttp2/1.47.0
     libarchive version : libarchive 3.6.2 zlib/1.2.13 bz2lib/1.0.8 libzstd/1.5.2
       virtual packages : __unix=0=0
                          __linux=5.10.161=0
                          __glibc=2.36=0
                          __archspec=1=x86_64
               channels : 
       base environment : /home/joaori/var/git/entwine/_dev/dev/micromamba
               platform : linux-64
```

</details>

Happy to provide additional info if required. Thank you.

### PR DESCRIPTION
**Pull request by connormanning**
S3 HEAD requests were being incorrectly routed to the generic HTTP functionality rather than the S3-specific implementation.  This was always an issue (these requests occur as an optional optimization prior to a GET), but was only recently made very apparent when retry backoffs were increased.  Closes #3955.

### CODE REVIEW

File: vendor/arbiter/arbiter.cpp [hunk 1]
```diff
@@ -2012,18 +2012,22 @@ S3::AuthFields S3::Auth::fields() const
     return S3::AuthFields(m_access, m_hidden, m_token);
 }
 
-std::unique_ptr<std::size_t> S3::tryGetSize(std::string rawPath) const
+std::unique_ptr<std::size_t> S3::tryGetSize(
+    const std::string rawPath,
```
Comment (hobu) [inline vendor/arbiter/arbiter.cpp:2016]: I assume that you'll want to alias tryGetSize with some default parameters for Headers and Query or you'll break the API, right?

**Review by hobu — APPROVED** [review]

**Comment by hobu** [comment]
Picked back to `2.5-maintenance` at 4e6fa9c4488492472de3a86ed61d9a041b96aa17
